name: Ruby

on:
  push:
    branches:
      - main

  pull_request:
  merge_group:
    types:
      - checks_requested
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}, Rails ${{ matrix.rails }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.2"
          - "3.3"
          - "3.4"
          - "4.0"
          - head
        rails:
          - "6.0"
          - "6.1"
          - "7.0"
          - "7.1"
          - "7.2"
          - "8.0"
          - "8.1"
          - "edge"
        exclude:
          - ruby: 3.4
            rails: 6.0
          - ruby: 3.4
            rails: 6.1
          - ruby: 3.4
            rails: 7.0
          - ruby: 4.0
            rails: 6.0
          - ruby: 4.0
            rails: 6.1
          - ruby: 4.0
            rails: 7.0
          - ruby: head
            rails: 6.0
          - ruby: head
            rails: 6.1
          - ruby: head
            rails: 7.0
          - ruby: 3.2
            rails: edge

    permissions:
      contents: read

    services:
      # Label used to access the service container
      db:
        # Docker Hub image
        image: postgres:16
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails_${{ matrix.rails }}.gemfile

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Set up Ruby ${{ matrix.ruby }} for Rails ${{ matrix.rails }}
        uses: ruby/setup-ruby@c4e5b1316158f92e3d49443a9d58b31d25ac0f8f # v1.306.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run rspec on Rails ${{ matrix.rails }}
        run: bin/appraisal rails-${{ matrix.rails }} rspec
        env:
          DB_HOST: localhost
  validate-dev-container:
    runs-on: ubuntu-latest
    name: Validate Devcontainer
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Build and run dev container task
        uses: devcontainers/ci@b63b30de439b47a52267f241112c5b453b673db5 #v0.3.1900000449
        with:
          runCmd: bin/rake spec # run the specs
